### ISSUE TITLE
Code Formatting: Flake8

### ISSUE THREAD

**Issue by AlexanderSenf** [JULIETYCL/DRS_client#1]
There are several conventions regarding how Python code should be formatted; these are called Style Guidelines. One style guideline is PEP8. There are tools that check Python code for common errors, and also for adherence to PEP8, such as `flake8`.

This issue is to check the existing code with flake8, and ensure it passes.

`sudo apt install flake8`
`flake8 *.py --max-line-length=120` 

This will check the two Python files, specifying a line length of 120 characters (default is 80, but often linger lines are preferred).

`flake8` is what is called a 'linter' - a static code analysis tool.

**Comment by JULIETYCL** [comment]
Thanks. Added.

**Comment by AlexanderSenf** [comment]
@JULIETYCL after PR #4 these formatting issues are relevant again

**Comment by JULIETYCL** [comment]
Kindly see PR #9

**Comment by AlexanderSenf** [comment]
Addressed by #9
