### ISSUE TITLE
Add Capability to decrypt a Crypt4GH file

### ISSUE THREAD

**Issue by AlexanderSenf** [JULIETYCL/DRS_client#8]
The download client should be able to decrypt files after download (this assumes functionality in the server not yet available to this client). 

The best way to add this functionality is by adding the Crypt4GH library (https://pypi.org/project/crypt4gh/) to the tool, and to expose the functionality required to decrypt.
A good way (one of several ways) to implement this would be by writing a convenience wrapper class just for the functionality you need (decrypt). 

Definition of Done:
(1) Use https://pypi.org/project/crypt4gh/ to create a key pair
(2) Use https://pypi.org/project/crypt4gh/ to encrypt a file with the public key of this key pair
(3) Use the Download Client to decrypt this file, using the private key of this key pair

**Comment by JULIETYCL** [comment]
I have added the capacity #12

**Comment by AlexanderSenf** [comment]
Addressed by #12
